apiVersion: v1
kind: Secret
metadata:
  name: elastic-credentials
  namespace: $(namespace)
type: Opaque
stringData:
  username: $(kibanaUsername)
  password: $(kibanaPass)   # 👈 set your own password here
